[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*",
    "https://cdn.freebiesupply.com/.*",
    "https://upload.wikimedia.org/.*",
    "https://uxwing.com/.*",
    "https://logowik.com/.*"
  ]

[build]
  command = "npm install && npm run build"
  publish = "out"
